/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utama;

import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldLoginNIK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        buttonRegister = new javax.swing.JButton();
        fieldLoginPassword = new javax.swing.JPasswordField();
        panelRegister = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldNIK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        fieldPassword1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelKiri.setBackground(new java.awt.Color(204, 204, 204));
        panelKiri.setPreferredSize(new java.awt.Dimension(580, 540));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PADULI SETAN");

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, java.awt.BorderLayout.WEST);

        panelKanan.setBackground(new java.awt.Color(51, 51, 51));
        panelKanan.setPreferredSize(new java.awt.Dimension(380, 540));
        panelKanan.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("LOGIN HEULA ATUH");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("NIK / ID Card");

        fieldLoginNIK.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Password");

        buttonLogin.setForeground(new java.awt.Color(51, 51, 51));
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonRegister.setForeground(new java.awt.Color(51, 51, 51));
        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(fieldLoginNIK)
                        .addComponent(jLabel4)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(buttonLogin)
                            .addGap(18, 18, 18)
                            .addComponent(buttonRegister))
                        .addComponent(fieldLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLoginNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonRegister))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        panelKanan.add(panelLogin, "cardLogin");

        panelRegister.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("DAPTAR HEULA ATUH");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("NIK / ID Card");

        fieldNIK.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nama Lengkap");

        fieldNama.setForeground(new java.awt.Color(51, 51, 51));

        buttonSubmit.setForeground(new java.awt.Color(51, 51, 51));
        buttonSubmit.setText("Submit Data");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Password");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Konfirmasi Password");

        fieldPassword.setForeground(new java.awt.Color(51, 51, 51));

        fieldPassword1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(fieldNIK, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(fieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(buttonSubmit)
                            .addComponent(jLabel8)
                            .addComponent(fieldPassword)
                            .addComponent(jLabel9)
                            .addComponent(fieldPassword1))
                        .addGap(55, 55, 55))))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonSubmit)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelKanan.add(panelRegister, "cardRegister");

        getContentPane().add(panelKanan, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        if (fieldNIK.getText().equals("") || fieldNama.getText().equals("") || fieldPassword.getText().equals("")){  
            JOptionPane.showMessageDialog(this, "ada form yang masih kosong");   
            
        } else if (!Arrays.equals(fieldPassword.getPassword(), fieldPassword1.getPassword())){
            JOptionPane.showMessageDialog(this, "kolom password beda");  
              
        } else {
            try {
                String sql = "INSERT INTO user VALUES ('"+fieldNIK.getText()+"','"
                        +fieldNama.getText()+"','"+fieldPassword.getText()+"', CURRENT_TIMESTAMP)";
                    java.sql.Connection conn=(Connection)Koneksi.configDB();
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    System.out.println(pst);
                    pst.execute();

                JOptionPane.showMessageDialog(this, "Anda berhasil mendaftar, silahkan masuk");
        
                CardLayout card = (CardLayout)panelKanan.getLayout();
                card.show(panelKanan, "cardLogin");
                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        CardLayout card = (CardLayout)panelKanan.getLayout();
        card.show(panelKanan, "cardRegister");
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        try {
            String sql = "SELECT * FROM user WHERE NIK='"+fieldLoginNIK.getText()+"' AND password='"+fieldLoginPassword.getText()+"'";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet r = pst.executeQuery();
            
            int baris = 0;
            while (r.next()){
                baris = r.getRow();
                String id = r.getString(1);
                Usr.usrId = id;
            }
            
            if (baris == 1){
                JOptionPane.showMessageDialog(null, "Login sukses",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);             

                String sql1 = "SELECT * FROM user WHERE NIK ='" + fieldLoginNIK.getText()+"';";
                java.sql.Connection conn1 = (Connection)Koneksi.configDB();
                java.sql.Statement stm = conn1.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql1);

                while(res.next()){
                    MainMenu d = new MainMenu();
                    //halaman utama
                    d.labelNama.setText(res.getString("namalengkap"));
                    d.labelNIK.setText(Usr.usrId);
                    //profil
                    d.labelNamaProfil.setText(res.getString("namalengkap"));
                    d.labelNIKProfil.setText(Usr.usrId);
                    d.labelTimestamp.setText(res.getString("dibuat"));
                    
                    this.dispose();
                    d.setVisible(true);
                } 
            } else {
                JOptionPane.showMessageDialog(null,
                        "Silahkan cek kembali username atau password",
                        "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JTextField fieldLoginNIK;
    private javax.swing.JPasswordField fieldLoginPassword;
    private javax.swing.JTextField fieldNIK;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldPassword1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegister;
    // End of variables declaration//GEN-END:variables
}
