/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utama;

import com.github.lgooddatepicker.components.TimePickerSettings;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        load_table();
        jumlah_perjalanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonProfil = new javax.swing.JButton();
        buttonCatat = new javax.swing.JButton();
        buttonLihat = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelNIK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        panelProfil = new javax.swing.JPanel();
        labeljudul = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelNamaProfil = new javax.swing.JLabel();
        labelNIKProfil = new javax.swing.JLabel();
        labelTimestamp = new javax.swing.JLabel();
        panelCatat = new javax.swing.JPanel();
        labeljudul1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        TimePickerSettings timeSettings = new TimePickerSettings();
        timeSettings.use24HourClockFormat();
        timeSettings.setDisplayToggleTimeMenuButton(false);
        timeSettings.setInitialTimeToNow();
        timePicker = new com.github.lgooddatepicker.components.TimePicker(timeSettings);
        fieldLokasi = new javax.swing.JTextField();
        fieldSuhu = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        panelLihat = new javax.swing.JPanel();
        labeljudul2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_perjalanan = new javax.swing.JTable();
        fieldCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKiri.setBackground(new java.awt.Color(51, 51, 51));
        panelKiri.setPreferredSize(new java.awt.Dimension(140, 540));

        buttonHome.setText("Halaman Utama");
        buttonHome.setForeground(new java.awt.Color(51, 51, 51));
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonProfil.setText("Profil");
        buttonProfil.setForeground(new java.awt.Color(51, 51, 51));
        buttonProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfilActionPerformed(evt);
            }
        });

        buttonCatat.setText("Catat Perjalanan");
        buttonCatat.setForeground(new java.awt.Color(51, 51, 51));
        buttonCatat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCatatActionPerformed(evt);
            }
        });

        buttonLihat.setText("Lihat Perjalanan");
        buttonLihat.setForeground(new java.awt.Color(51, 51, 51));
        buttonLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLihatActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.setForeground(new java.awt.Color(51, 51, 51));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("PaduliSetan");
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonProfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCatat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(buttonLihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(buttonHome)
                .addGap(18, 18, 18)
                .addComponent(buttonProfil)
                .addGap(18, 18, 18)
                .addComponent(buttonCatat)
                .addGap(18, 18, 18)
                .addComponent(buttonLihat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(buttonLogout)
                .addGap(38, 38, 38))
        );

        getContentPane().add(panelKiri, java.awt.BorderLayout.WEST);

        panelKanan.setBackground(new java.awt.Color(204, 204, 204));
        panelKanan.setPreferredSize(new java.awt.Dimension(820, 540));
        panelKanan.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(204, 204, 204));

        labelNama.setText("namalengkap");
        labelNama.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelNama.setForeground(new java.awt.Color(51, 51, 51));

        labelNIK.setText("nik");
        labelNIK.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelNIK.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setText("Selamat datang di aplikasi Paduli Setan!");
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Total perjalanan anda selama ini adalah :");

        total.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(51, 51, 51));
        total.setText("total");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total))
                    .addComponent(jLabel4)
                    .addComponent(labelNIK)
                    .addComponent(labelNama))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNIK)
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(101, 101, 101)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(total))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        panelKanan.add(panelHome, "cardHome");

        panelProfil.setBackground(new java.awt.Color(204, 204, 204));

        labeljudul.setText("Profil Anda");
        labeljudul.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labeljudul.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setText("Nama Lengkap");
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setText("NIK");
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setText("Tanggal Mendaftar");
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));

        labelNamaProfil.setText("nama");
        labelNamaProfil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelNamaProfil.setForeground(new java.awt.Color(51, 51, 51));

        labelNIKProfil.setText("nik");
        labelNIKProfil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelNIKProfil.setForeground(new java.awt.Color(51, 51, 51));

        labelTimestamp.setText("timestamp");
        labelTimestamp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelTimestamp.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeljudul)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(56, 56, 56)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTimestamp)
                            .addComponent(labelNIKProfil)
                            .addComponent(labelNamaProfil))))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        panelProfilLayout.setVerticalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(labeljudul)
                .addGap(67, 67, 67)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNamaProfil))
                .addGap(18, 18, 18)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelNIKProfil))
                .addGap(18, 18, 18)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelTimestamp))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        panelKanan.add(panelProfil, "cardProfil");

        panelCatat.setBackground(new java.awt.Color(204, 204, 204));

        labeljudul1.setText("Catat Perjalanan");
        labeljudul1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labeljudul1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setText("Tanggal");
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setText("Jam");
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setText("Lokasi");
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setText("Suhu");
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));

        buttonSubmit.setText("Submit Data");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCatatLayout = new javax.swing.GroupLayout(panelCatat);
        panelCatat.setLayout(panelCatatLayout);
        panelCatatLayout.setHorizontalGroup(
            panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeljudul1)
                    .addGroup(panelCatatLayout.createSequentialGroup()
                        .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(94, 94, 94)
                        .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldLokasi)
                            .addComponent(buttonSubmit)
                            .addComponent(fieldSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        panelCatatLayout.setVerticalGroup(
            panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatatLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labeljudul1)
                .addGap(74, 74, 74)
                .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(timePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCatatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(buttonSubmit)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        panelKanan.add(panelCatat, "cardCatat");

        panelLihat.setBackground(new java.awt.Color(204, 204, 204));

        labeljudul2.setText("Lihat Perjalanan");
        labeljudul2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labeljudul2.setForeground(new java.awt.Color(51, 51, 51));

        table_perjalanan.setAutoCreateRowSorter(true);
        table_perjalanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_perjalanan);

        fieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCariKeyReleased(evt);
            }
        });

        jLabel2.setText("Cari sesuatu di tabel ini");
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelLihatLayout = new javax.swing.GroupLayout(panelLihat);
        panelLihat.setLayout(panelLihatLayout);
        panelLihatLayout.setHorizontalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLihatLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLihatLayout.createSequentialGroup()
                        .addComponent(labeljudul2)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLihatLayout.setVerticalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLihatLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeljudul2)
                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        panelKanan.add(panelLihat, "cardLihat");

        getContentPane().add(panelKanan, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        CardLayout card = (CardLayout)panelKanan.getLayout();
        card.show(panelKanan, "cardHome");
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfilActionPerformed
        CardLayout card = (CardLayout)panelKanan.getLayout();
        card.show(panelKanan, "cardProfil");
    }//GEN-LAST:event_buttonProfilActionPerformed

    private void buttonCatatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCatatActionPerformed
        CardLayout card = (CardLayout)panelKanan.getLayout();
        card.show(panelKanan, "cardCatat");
    }//GEN-LAST:event_buttonCatatActionPerformed

    private void buttonLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLihatActionPerformed
        CardLayout card = (CardLayout)panelKanan.getLayout();
        card.show(panelKanan, "cardLihat");
    }//GEN-LAST:event_buttonLihatActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin Keluar?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Silahkan login kembali");
            
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        try{
            String sql = "INSERT INTO perjalanan (`tanggal`, `jam`, `lokasi`, `suhu_tubuh`, `ditambah_oleh`) VALUES ('"+datePicker.getDateStringOrEmptyString()+"','"
                        +timePicker.getText()+"','"+fieldLokasi.getText()+"','"
                        +fieldSuhu.getText()+"','"+Usr.usrId+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data telah terkirim", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            update_table();
            jumlah_perjalanan();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void fieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCariKeyReleased
        DefaultTableModel model = (DefaultTableModel) table_perjalanan.getModel();
        
        String cari = fieldCari.getText();
        
        TableRowSorter tr = new TableRowSorter(model);
        table_perjalanan.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_fieldCariKeyReleased
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Tanggal");
        model.addColumn("Jam");
        model.addColumn("Lokasi");
        model.addColumn("Suhu Tubuh");      
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT * FROM perjalanan WHERE ditambah_oleh ='" + Usr.usrId+"';";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            table_perjalanan.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void update_table() {     
        DefaultTableModel model = (DefaultTableModel) table_perjalanan.getModel();
        model.setRowCount(0);
        
        load_table();
    }
    
    private void jumlah_perjalanan() {
        try {
            String sql = "SELECT COUNT(*) AS jumlahperjalanan FROM perjalanan;";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet s = pst.executeQuery();
            
            s.next();
            total.setText(String.valueOf(s.getInt(1)));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ada yang salah", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCatat;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLihat;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonProfil;
    private javax.swing.JButton buttonSubmit;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JTextField fieldLokasi;
    private javax.swing.JTextField fieldSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelNIK;
    public javax.swing.JLabel labelNIKProfil;
    public javax.swing.JLabel labelNama;
    public javax.swing.JLabel labelNamaProfil;
    public javax.swing.JLabel labelTimestamp;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labeljudul1;
    private javax.swing.JLabel labeljudul2;
    private javax.swing.JPanel panelCatat;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLihat;
    private javax.swing.JPanel panelProfil;
    private javax.swing.JTable table_perjalanan;
    private com.github.lgooddatepicker.components.TimePicker timePicker;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
